### ISSUE TITLE
Move code to a subdirectory

### ISSUE THREAD

**Issue by dpsanders** [WyLyu/UPOsHam#8]
I suggest moving the actual code files to a subdirectory of the repository, e.g. `src`.

**Comment by dpsanders** [comment]
Part of JOSS review @ https://github.com/openjournals/joss-reviews/issues/1684

**Comment by JoshKarpel** [comment]
It might be best to move to a structure like that explained in the first part of this article: https://docs.python-guide.org/writing/structure/ . That will get you on the road to adding a `setup.py` file so that this package becomes installable. In particular, I'd like there to be some separation between the examples and the package code.

**Comment by Shibabrat** [comment]
#26 I've reopened this pull request to point out that I've addressed this issue with moving the code files to separate directories. For example, the methods are in src and problem applications are in examples.

**Comment by dpsanders** [comment]
You don't actually need to reopen the pull request to add comments. On the other hand, you might want to leave them open for comments before they are merged.

**Comment by JoshKarpel** [comment]
I believe this has been resolved. @dpsanders agree?
